### ISSUE TITLE
Can't find native library on mac

### ISSUE THREAD

**Issue by fcyen** [CAFDataProcessing/worker-languagedetection#48]
Hi, I've added the `language-detector-cld2` library as a dependency in my project
```
dependencies {
    // https://mavenlibs.com/maven/dependency/com.github.cafdataprocessing/language-detection-cld2
    implementation 'com.github.cafdataprocessing:language-detection-cld2:3.5.2-1079'
    ...
}
```
and added the environment variable `cld2.location=\` where my dylib files are included in the project as such:
```
<project root>
|- src
|   -- main
|        -- resources
|             -- libcld2.dylib
```

but I'm getting this error
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'linux/libcld2.so':
dlopen(liblinux/libcld2.so.dylib, 0x0009): tried: '/Users/fcyen/Library/Java/JavaVirtualMachines/corretto-17.0.3/Contents/Home/bin/./liblinux/libcld2.so.dylib' (no such file), '/Users/fcyen/Library/Java/JavaVirtualMachines/corretto-17.0.3/Contents/Home/bin/../lib/liblinux/libcld2.so.dylib' (no such file), 'liblinux/libcld2.so.dylib' (no such file)
dlopen(liblinux/libcld2.so.dylib, 0x0009): tried: '/Users/fcyen/Library/Java/JavaVirtualMachines/corretto-17.0.3/Contents/Home/bin/./liblinux/libcld2.so.dylib' (no such file), '/Users/fcyen/Library/Java/JavaVirtualMachines/corretto-17.0.3/Contents/Home/bin/../lib/liblinux/libcld2.so.dylib' (no such file), 'liblinux/libcld2.so.dylib' (no such file)
Native library (darwin/liblinux/libcld2.so.dylib) not found in resource path (/Users/fcyen/Code/personal/test-cld-2/build/classes/java/main:/Users/fcyen/Code/personal/test-cld-2/build/resources/main:/Users/fcyen/.gradle/caches/modules-2/files-2.1/com.github.cafdataprocessing/language-detection-cld2/3.5.2-1079/9424361b05f7c5bb6e6ba6bab7441b4d5a78868a/language-detection-cld2-3.5.2-1079.jar:/Users/fcyen/.gradle/caches/modules-2/files-2.1/com.github.cafdataprocessing/language-detection/3.5.2-1079/d501a1ea3151eca8d49338f417ddbf59ab8e859e/language-detection-3.5.2-1079.jar:/Users/fcyen/.gradle/caches/modules-2/files-2.1/net.java.dev.jna/jna/5.5.0/e0845217c4907822403912ad6828d8e0b256208/jna-5.5.0.jar:/Users/fcyen/.gradle/caches/modules-2/files-2.1/commons-io/commons-io/2.11.0/a2503f302b11ebde7ebc3df41daebe0e4eea3689/commons-io-2.11.0.jar:/Users/fcyen/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.26/77100a62c2e6f04b53977b9f541044d7d722693d/slf4j-api-1.7.26.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
	at com.sun.jna.Library$Handler.<init>(Library.java:192)
	at com.sun.jna.Native.loadLibrary(Native.java:646)
	at com.sun.jna.Native.loadLibrary(Native.java:630)
	at com.hpe.caf.languagedetection.cld2.Cld2Wrapper.<init>(Cld2Wrapper.java:46)
	at com.hpe.caf.languagedetection.cld2.Cld2Detector.detectLanguage(Cld2Detector.java:50)
	at com.hpe.caf.languagedetection.cld2.Cld2Detector.detectLanguage(Cld2Detector.java:113)
	at com.cld2.test.TranslationManager.main(TranslationManager.java:29)
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(liblinux/libcld2.so.dylib, 0x0009): tried: '/Users/fcyen/Library/Java/JavaVirtualMachines/corretto-17.0.3/Contents/Home/bin/./liblinux/libcld2.so.dylib' (no such file), '/Users/fcyen/Library/Java/JavaVirtualMachines/corretto-17.0.3/Contents/Home/bin/../lib/liblinux/libcld2.so.dylib' (no such file), 'liblinux/libcld2.so.dylib' (no such file)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 8 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(liblinux/libcld2.so.dylib, 0x0009): tried: '/Users/fcyen/Library/Java/JavaVirtualMachines/corretto-17.0.3/Contents/Home/bin/./liblinux/libcld2.so.dylib' (no such file), '/Users/fcyen/Library/Java/JavaVirtualMachines/corretto-17.0.3/Contents/Home/bin/../lib/liblinux/libcld2.so.dylib' (no such file), 'liblinux/libcld2.so.dylib' (no such file)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 8 more
	Suppressed: java.io.IOException: Native library (darwin/liblinux/libcld2.so.dylib) not found in resource path (/Users/fcyen/Code/personal/test-cld-2/build/classes/java/main:/Users/fcyen/Code/personal/test-cld-2/build/resources/main:/Users/fcyen/.gradle/caches/modules-2/files-2.1/com.github.cafdataprocessing/language-detection-cld2/3.5.2-1079/9424361b05f7c5bb6e6ba6bab7441b4d5a78868a/language-detection-cld2-3.5.2-1079.jar:/Users/fcyen/.gradle/caches/modules-2/files-2.1/com.github.cafdataprocessing/language-detection/3.5.2-1079/d501a1ea3151eca8d49338f417ddbf59ab8e859e/language-detection-3.5.2-1079.jar:/Users/fcyen/.gradle/caches/modules-2/files-2.1/net.java.dev.jna/jna/5.5.0/e0845217c4907822403912ad6828d8e0b256208/jna-5.5.0.jar:/Users/fcyen/.gradle/caches/modules-2/files-2.1/commons-io/commons-io/2.11.0/a2503f302b11ebde7ebc3df41daebe0e4eea3689/commons-io-2.11.0.jar:/Users/fcyen/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.26/77100a62c2e6f04b53977b9f541044d7d722693d/slf4j-api-1.7.26.jar)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1095)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:276)
		... 8 more
```
Any ideas how to solve it?

**Comment by fcyen** [comment]
Closing this issue as I've switch to a linux environment
